version: "3.9"

services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes:
      - "epamproject:/var/lib/postgresql/data"

volumes:
  epamproject: